---
- name: checking interface status
  ios_command:
    commands:
      - Show interface {{ interfacenumber}}
  register: status
  ignore_errors: true

- debug: var=status
  ignore_errors: true

- name: checking interface status
  ios_command:
    commands:
      - Show run interface {{ interfacenumber }}
  register: run_status
  ignore_errors: true

- debug: var=run_status
  ignore_errors: true

- name: encoding
  shell: echo {{ status.stdout }} | base64
  register: status_encode

- name: encoding
  shell: echo {{ run_status.stdout }} | base64
  register: run_status_encode

- command: date +'%d/%m/%Y_%H:%M:%S'
  register: timestamp

- name: "Create output attachment in incident"
  uri:
   body:
     attachments:
       attachment:
         file: "{{status_encode.stdout}}"
         filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_intstatus.txt"        
     number: "{{incnumber}}"
   body_format: json
   force_basic_auth: true
   method: POST
   password: YZ3uS3f2h.!=bcRztTdE
   status_code: 201
   url: "https://xml.itsmstaging.accenture.com/ITSMXML/api/i_Adevinta_INC_toACCSN/Adevinta/number"
   user: A04681RTSAdevintaToSN
  ignore_errors: true

- name: "Create output attachment in incident"
  uri:
   body:
     attachments:
       attachment:
         file: "{{run_status_encode.stdout}}"
         filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_runstatus.txt"
     number: "{{incnumber}}"
   body_format: json
   force_basic_auth: true
   method: POST
   password: YZ3uS3f2h.!=bcRztTdE
   status_code: 201
   url: "https://xml.itsmstaging.accenture.com/ITSMXML/api/i_Adevinta_INC_toACCSN/Adevinta/number"
   user: A04681RTSAdevintaToSN
  ignore_errors: true
