---
- name: High CPU Utilization
  block: 
   - name: Triggering high cpu utilization command on device
     ios_command:
       commands:
          sh processes cpu sorted
     register: cpu_util

   - debug: var=cpu_util

   - name: Triggering high cpu utilization history
     ios_command:
       commands:
          sh processes cpu history
     register: cpu_his
 
   - debug: var=cpu_his

   - name: encoding
     shell: echo {{ cpu_util.stdout }} | base64
     register: cpu_util_encode

   - name: encoding
     shell: echo {{ cpu_his.stdout }} | base64
     register: cpu_his_encode

   - command: date +'%d/%m/%Y_%H:%M:%S'
     register: timestamp

   - name: "Create output attachment in incident"
     uri:
       body:
         attachments:
           attachment:
             file: "{{cpu_util_encode.stdout}}"
             filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_util.txt"
         number: "{{ incnumber }}"
       body_format: json
       force_basic_auth: true
       method: POST
       password: "{{servicenow_password}}"
       status_code: 201
       url: "https://xml.itsm.accenture.com/ITSMXML/api/i_adevinta_inc_toaccsn/Adevinta/number"
       user: "{{servicenow_user}}"
     ignore_errors: yes

   - name: "Create output attachment in incident"
     uri:
       body:
         attachments:
           attachment:
             file: "{{cpu_his_encode.stdout}}"
             filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_hist.txt"
         number: "{{ incnumber }}"
       body_format: json
       force_basic_auth: true
       method: POST
       password: "{{servicenow_password}}"
       status_code: 201
       url: "https://xml.itsm.accenture.com/ITSMXML/api/i_adevinta_inc_toaccsn/Adevinta/number"
       user: "{{servicenow_user}}"
     ignore_errors: yes

  rescue:
   - name: Print when errors
     ansible.builtin.debug:
       msg: "Code execution failed kindly check it manually."
     register: error
   
   - debug: var=error

   - name: "Create output attachment in incident"
     uri:
       body: {"number":"{{ incnumber }}", "work_notes":"{{error.msg}}"}
       body_format: json
       force_basic_auth: true
       method: POST
       password: "{{servicenow_password}}"
       status_code: 201
       url: "https://xml.itsm.accenture.com/ITSMXML/api/i_adevinta_inc_toaccsn/Adevinta/number"
       user: "{{servicenow_user}}"
     ignore_errors: true
