---
- name: Triggering high cpu utilization command on device
  ios_command:
    commands:
      - sh processes cpu sorted
  register: cpu_util
  ignore_errors: true
- debug: var=cpu_util

- name: Triggering high cpu utilization history
  ios_command:
    commands:
      - sh processes cpu history
  register: cpu_his
  ignore_errors: true
- debug: var=cpu_his


- name: encoding
  shell: echo {{ cpu_util.stdout }} | base64
  register: cpu_util_encode

- name: encoding
  shell: echo {{ cpu_his.stdout }} | base64
  register: cpu_his_encode

- command: date +'%d/%m/%Y_%H:%M:%S'
  register: timestamp

- name: "Create output attachment in incident"
  uri:
   body:
     attachments:
       attachment:
         file: "{{cpu_util_encode.stdout}}"
         filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_util.txt"
     number: "{{ incnumber }}"
   body_format: json
   force_basic_auth: true
   method: POST
   password: YZ3uS3f2h.!=bcRztTdE
   status_code: 201
   url: "https://xml.itsmstaging.accenture.com/ITSMXML/api/i_Adevinta_INC_toACCSN/Adevinta/number"
   user: A04681RTSAdevintaToSN

- name: "Create output attachment in incident"
  uri:
   body:
     attachments:
       attachment:
         file: "{{cpu_his_encode.stdout}}"
         filename: "'{{incnumber}}'_'{{timestamp.stdout}}'_hist.txt"
     number: "{{ incnumber }}"
   body_format: json
   force_basic_auth: true
   method: POST
   password: YZ3uS3f2h.!=bcRztTdE
   status_code: 201
   url: "https://xml.itsmstaging.accenture.com/ITSMXML/api/i_Adevinta_INC_toACCSN/Adevinta/number"
   user: A04681RTSAdevintaToSN
